accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

bbs/urls.py
from django.urls import path
from . import views

app_name = 'bbs'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
    path('search/', views.search, name='search'),
]

config/urls.py
## プロジェクト全体のルーティングを記述
"""
URL configuration for config project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bbs/', include('bbs.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')), ## ユーザー認証用のビュー
    path('', RedirectView.as_view(url='/bbs/')),
]

accounts/models.py
from django.db import models

# Create your models here.

bbs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Article(models.Model):
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.PROTECT)  ##フィールドオプションon_deleteは、関連先のオブジェクトが削除された際にそのオブジェクト自身がとる挙動を指定
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

    ## 汎用ビューでは、データの保存後にget_absolute_urlが呼び出されるようになっている（汎用ビューの種類）
    def get_absolute_url(self):

        ## urlpatternsでname='〇〇'と指定したURLを呼び出す関数
        return reverse('bbs:detail', kwargs={'pk' : self.pk})

bbs/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField(
        label='',
        max_length=50,
        widget=forms.TextInput(
            attrs={
                'class':'form-control me-2',
                'placeholder':'キーワードを入力',
                'aria-label':'Search',
                }
            ),
        )

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

# Create your views here.

class SignUpView(generic.CreateView):
    form_class = UserCreationForm  ## form_classの種類
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

bbs/views.py
from django.shortcuts import render
from django.views import generic ## 汎用ビュー
from .models import Article 
from django.urls import reverse_lazy
from .forms import SearchForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied

# Create your views here.
class IndexView(generic.ListView):
    model = Article
    template_name = 'bbs/index.html'


class DetailView(generic.DetailView):
    model = Article
    template_name = 'bbs/detail.html'


class CreateView(LoginRequiredMixin, generic.edit.CreateView):
    model = Article
    template_name = 'bbs/create.html'
    fields = ['content'] ##（多分fieldsはテーブル項目に該当？）

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(CreateView, self).form_valid(form)


class UpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    model = Article
    template_name = 'bbs/create.html'
    fields = ['content']

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if obj.author != self.request.user:
            raise PermissionDenied('編集権限がありません。')

        return super(UpdateView, self).dispatch(request, *args, **kwargs)


class DeleteView(LoginRequiredMixin, generic.edit.DeleteView):
    model = Article
    template_name = 'bbs/delete.html'
    success_url = reverse_lazy('bbs:index')


def search(request):
    articles = None
    searchform = SearchForm(request.GET) # request.GETのプロパティのキー名とSearchFormのフィールド変数が`query`で一致しているため自動的に代入

    if searchform.is_valid(): #フォームデータの検証とcleaned_dataの作成
        query = searchform.cleaned_data['query']
        articles = Article.objects.filter(content__icontains=query)
    
    return render(request, 'bbs/results.html', {'articles':articles, 'searchform':searchform})

templates/accounts/signup.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<h1 class="mt-5">Djnagoで作るサインアップ機能</h1>
<section>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="サインアップ" size="md" %}
    </form>
</section>

<div class="mt-3"><a onclick='JavaScript:history.back()'>
        {% bootstrap_button button_type="submit" button_class="btn-secondary" content="戻る" %}
    </a></div>
{% endblock %}

templates/base.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <title>Djangoを使ってみよう！</title>
    <style>
        .container {
            background-color: #efefef
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-dark bg-dark" aria-label="First navbar example">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'bbs:index' %}">100チャンネル</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample01"
                aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExample01">
                <ul class="navbar-nav me-auto mb-2">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'bbs:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                        <span class="nav-link active">
                            <a>{{ user }}でログイン中</a>
                            <form action="{% url 'logout' %}" method="post">
                                {% csrf_token %}
                                {% bootstrap_button button_type="submit" button_class="btn-success" content="ログアウト" size="md" %}
                            </form>
                            {% else %}
                            <form action="{% url 'login' %}" method="post">
                                {% csrf_token %}
                                {% bootstrap_button button_type="submit" button_class="btn-success" content="ログイン" size="md" %}
                            </form>
                        </span>
                        {% endif %}
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-bs-toggle="dropdown"
                            aria-expanded="false">Dropdown</a>
                        <ul class="dropdown-menu" aria-labelledby="dropdown01">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="d-flex" method="get" action="{% url 'bbs:search' %}">
                    {{ searchform.query }}
                    <button class="btn btn-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</body>

</html>

templates/bbs/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<h1 class="mt-5">投稿の{{ object|yesno:'編集,新規作成' }}</h1>

<form action="" , method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content=object|yesno:"更新,作成" size="md" %}
</form>

<div class="mt-3"><a onclick='JavaScript:history.back()'>
        {% bootstrap_button button_type="submit" button_class="btn-secondary" content="戻る" %}
    </a></div>
{% endblock %}

templates/bbs/delete.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<h1 class="mt-5">投稿の削除</h1>
<p>{{ article.id }}の投稿を削除しますか？</p>

<form action="" method="post">{% csrf_token %}
    {% bootstrap_button button_type="submit" content="削除" size="md" button_class="btn-danger" %}
</form>

<div class="mt-3">
    <a onclick="JavaScript:history.back()">
        {% bootstrap_button button_type="submit" content="戻る" size="md" button_class="btn-secondary" %}
    </a>
</div>
{% endblock %}

templates/bbs/detail.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<h1 class="mt-5">{{ article.id }}の投稿詳細ページ</h1>

<div class="card bg-light shadow-sm mt-3">
    <div class="card-body">
        <p>{{ article.author }} : {{ article.created_at }}</p>
        <p>最終更新 : {{ article.updated_at }}</p>
        <p>{{ article.content }}</p>

        {% if request.user.id == object.author_id %}
        <p><a href='{% url "bbs:update" article.pk %}'>
                {% bootstrap_button button_type="submit" button_class="btn-success" content="編集" size="md" %}
        </a></p>
        <p><a href="{% url 'bbs:delete' article.pk %}">
                {% bootstrap_button button_type="submit" button_class="btn-danger" content="削除" size="md" %}
        </a></p>
        {% endif %}

    </div>
</div>

<div class="mt-3">
    <p><a href='{% url "bbs:index" %}'>
            {% bootstrap_button button_type="submit" button_class="btn-secondary" content="一覧ページへ戻る" size="md" %}
        </a></p>
</div>

{% endblock %}

templates/bbs/index.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<h1 class="mt-5">CRUDアプリを作ってみよう！</h1>
{% for article in object_list %}
<div class="card bg-light shadow-sm mt-3">
    <div class="card-body">
        <p>{{ article.id }} : {{ article.author }} : {{ article.created_at }}</p>
        <p><a href='{% url "bbs:detail" article.id %}'>{{ article.content }}</a></p>
    </div>
</div>
{% endfor %}

{% if user.is_authenticated %}
<div class="mt-3">
    <a href="{% url 'bbs:create' %}">
        {% bootstrap_button button_type="submit" content="新規投稿" size="md" %}
        <!-- <button onclick="location.href='{% url 'bbs:create' %}'">新規投稿</button> -->
    </a>
</div>
{% endif %}
{% endblock %}

</html>

templates/bbs/results.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<h1 class="mt-5">検索結果</h1>
{% if articles %}
{% for article in articles %}
<div class="card bg-light shadow-sm mt-3">
    <div class="card-body">
        <p>{{ article.id }} : {{ article.author }} : {{ article.created_at }}</p>
        <p><a href='{% url "bbs:detail" article.id %}'>{{ article.content }}</a></p>
    </div>
</div>
{% endfor %}
{% else %}
<p>{{ searchform.query.value }}に一致する投稿はありません。</p>
{% endif %}

<div class="mt-3">
    <a onclick='JavaScript:history.back()'>
        {% bootstrap_button button_type="submit" button_class="btn-secondary" content="戻る" %}
    </a>
</div>
{% endblock %}

</html>